%> \file
%> Steepest descent algorithm. Implementation of algorithm 11.3 of \cite Bier06-book
%> 
%> @author Michel Bierlaire
%> @date Sun Apr  6 00:15:35 2014
%> @ingroup Algorithms

%> Applies the steepest descent algorithm with line search to solve \f$\min_x f(x)\f$ where \f$f:\mathbb{R}^n\to\mathbb{R}\f$
%> @param obj the name of the Octave function defining f(x) and its derivatives
%> @param x0 the starting point
%> @param eps  algorithm stops if \f$\|F(x)\| \leq \varepsilon \f$. 
%> @param maxiter maximum number of iterations (Default: 100)
%> @return [solution,iteres,niter] solution: local minimum of the function, iteres: sequence of iterates generated by the algorithm, niter: total number of iterations
function [solution, iteres, niter] = a1103steepest(obj,x0,eps,maxiter = 100)
  xk = x0 ;
  [f,g] = feval(obj,xk)   ;
  iteres = zeros(1+ maxiter,4) ;
  k = 0 ;
  iteres(1,:) = [xk'  f  norm(g) ] ;
  do
    alpha = a1102linesearch(obj,xk,-g,1.0,0.3,0.7,2) ;
    xk = xk - alpha * g ;
    [f,g] = feval(obj,xk);
    k=k+1 ; 
    iteres(k+1,:) = [xk' f  norm(g) ] ;
  until (norm(g) <= eps || k >= maxiter)
  solution = xk ;
  niter = k ;
endfunction
