%> \file
%> Newton's method with line search . Implementation of algorithm 11.5 of \cite Bier06-book
%> 
%> @author Michel Bierlaire
%> @date Wed Apr  9 16:37:12 2014
%> @ingroup Algorithms

%> Applies Newton's algorithm with line search to solve \f$\min_x f(x)\f$ where \f$f:\mathbb{R}^n\to\mathbb{R}\f$
%> @param obj the name of the Octave function defining f(x) and its derivatives
%> @param x0 the starting point
%> @param eps  algorithm stops if \f$\|F(x)\| \leq \varepsilon \f$. 
%> @param maxiter maximum number of iterations (Default: 100)
%> @return [solution,iteres,niter] solution: local minimum of the function, iteres: sequence of iterates generated by the algorithm, niter: total number of iterations
function [solution,iteres,niter] = a1105newton(obj,x0,eps,maxiter=100)
  iteres = zeros(1+ maxiter,4) ;
  xk = x0 ;
  [f,g,H] = feval(obj,xk)  ;
  iteres(1,:) = [xk'  f  norm(g) ] ;
  k = 0 ;
  do
    [L,tau] = a1104modchol(H) ;
    z = L \ g ;
    d = - L' \ z ;
    alpha = a1102linesearch(obj,xk,d,1.0,0.3,0.7,2) ;
    xk = xk + alpha * d ;
    [f,g,H] = feval(obj,xk);
    k=k+1 ; 
    iteres(k+1,:) = [xk' f  norm(g) ] ;
  until (norm(g) <= eps || k >= maxiter)
  solution = xk ;
  niter = k ;

endfunction
